export type Chain = {
  name: string;
  logoUrl: string;
  keywords: string[];
};

export const chains: Chain[] = [
  { name: "Advanced Sepolia Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["advanced", "sepolia"] },
  { name: "Astarzk Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["astarzk", "sepolia"] },
  { name: "Automata Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["automata"] },
  { name: "Azalea Mantle Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["azalea", "mantle"] },
  { name: "Arbitrum Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["arbitrum", "sepolia"] },
  { name: "Avalanche Fuji", logoUrl: "/Chains/ethereum.svg", keywords: ["avalanche", "fuji", "avax"] },
  { name: "Aleph Zero Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["aleph", "zero"] },
  { name: "Avara - r-testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["avara", "r-testnet"] },
  { name: "Beam Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["beam", "sepolia"] },
  { name: "Blast Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["blast", "sepolia"] },
  { name: "Boba Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["boba", "sepolia"] },
  { name: "Berachain Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["berachain", "sepolia"] },
  { name: "BOB Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["bob", "sepolia"] },
  { name: "Base Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["base", "sepolia"] },
  { name: "Bitlayer Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["bitlayer"] },
  { name: "BitTorrent Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["bittorrent", "btt"] },
  { name: "Canto Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["canto"] },
  { name: "Celo Alfajores", logoUrl: "/Chains/ethereum.svg", keywords: ["celo", "alfajores"] },
  { name: "Chiliz Spicy Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["chiliz", "spicy"] },
  { name: "Core Blockchain Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["core"] },
  { name: "COTI Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["coti"] },
  { name: "Cronos Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["cronos"] },
  { name: "Cronos aEVM Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["cronos", "aevm"] },
  { name: "Crescent Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["crescent"] },
  { name: "DODOchain Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["dodochain", "dodo"] },
  { name: "EKU Chain Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["eku"] },
  { name: "ENALS Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["enals"] },
  { name: "Ethereum Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["ethereum", "sepolia", "eth"] },
  { name: "Ethereum Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["ethereum", "eth"] },
  { name: "Etherlink Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["etherlink"] },
  { name: "Filecoin - Calibration Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["filecoin", "calibration"] },
  { name: "Flare Testnet Coston2", logoUrl: "/Chains/ethereum.svg", keywords: ["flare", "coston2"] },
  { name: "Flow EVM Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["flow", "evm"] },
  { name: "Fraximal Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["fraximal"] },
  { name: "Gnosis Chain Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["gnosis"] },
  { name: "HeatKey Chain Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["heatkey"] },
  { name: "Hedera Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["hedera"] },
  { name: "Holesky", logoUrl: "/Chains/ethereum.svg", keywords: ["holesky"] },
  { name: "Hyperliquid EVM Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["hyperliquid", "evm"] },
  { name: "Irys Testnet v1", logoUrl: "/Chains/ethereum.svg", keywords: ["irys", "v1"] },
  { name: "Kala Kairus Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["kala", "kairus"] },
  { name: "Kava Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["kava"] },
  { name: "Kroma Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["kroma", "sepolia"] },
  { name: "Lava Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["lava", "sepolia"] },
  { name: "Linea Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["linea", "sepolia"] },
  { name: "Lisk Sepolia Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["lisk", "sepolia"] },
  { name: "Lumio", logoUrl: "/Chains/ethereum.svg", keywords: ["lumio"] },
  { name: "Manta Pacific Sepolia Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["manta", "pacific", "sepolia"] },
  { name: "Mantle Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["mantle", "sepolia"] },
  { name: "MegaETH Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["megaeth"] },
  { name: "Merlin Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["merlin"] },
  { name: "Metal L2 Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["metal"] },
  { name: "Metis Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["metis", "sepolia"] },
  { name: "Mezzo Mantle Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["mezzo", "mantle"] },
  { name: "Mint Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["mint", "sepolia"] },
  { name: "Mode Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["mode", "sepolia"] },
  { name: "Monad Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["monad"] },
  { name: "Morph Holesky", logoUrl: "/Chains/ethereum.svg", keywords: ["morph", "holesky"] },
  { name: "Oasis Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["oasis", "sepolia"] },
  { name: "OP Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["op", "sepolia", "optimism"] },
  { name: "opBNB Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["opbnb", "bnb"] },
  { name: "Plume Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["plume"] },
  { name: "Polygon Amoy", logoUrl: "/Chains/ethereum.svg", keywords: ["polygon", "amoy", "matic"] },
  { name: "Polygon zkEVM Cardona", logoUrl: "/Chains/ethereum.svg", keywords: ["polygon", "zkevm", "cardona", "matic"] },
  { name: "PulseChain Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["pulsechain"] },
  { name: "RAIR Chain Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["rair"] },
  { name: "RSK Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["rsk", "rootstock"] },
  { name: "Ronin Saigon", logoUrl: "/Chains/ethereum.svg", keywords: ["ronin", "saigon"] },
  { name: "Rootstock Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["rootstock", "rsk"] },
  { name: "Scroll Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["scroll", "sepolia"] },
  { name: "Sei Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["sei"] },
  { name: "Shibarium Puppynet", logoUrl: "/Chains/ethereum.svg", keywords: ["shibarium", "puppynet"] },
  { name: "Beronix-Merato", logoUrl: "/Chains/ethereum.svg", keywords: ["beronix", "merato"] },
  { name: "Seele Blaze", logoUrl: "/Chains/ethereum.svg", keywords: ["seele", "blaze"] },
  { name: "Sophon Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["sophon"] },
  { name: "Substrate EVM Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["substrate", "evm"] },
  { name: "Superposition Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["superposition"] },
  { name: "Superseed Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["superseed", "sepolia"] },
  { name: "Syscoin Tanenbaum Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["syscoin", "tanenbaum"] },
  { name: "Taiko Helia", logoUrl: "/Chains/ethereum.svg", keywords: ["taiko", "helia"] },
  { name: "Telos EVM Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["telos", "evm"] },
  { name: "Telos aEVM Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["telos", "aevm"] },
  { name: "Tenet Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["tenet"] },
  { name: "Treasure Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["treasure"] },
  { name: "Ursichain Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["ursichain", "sepolia"] },
  { name: "Viction Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["viction"] },
  { name: "Wemix Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["wemix"] },
  { name: "World Chain Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["world", "chain", "sepolia"] },
  { name: "X Layer Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["xlayer", "x layer"] },
  { name: "Xai Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["xai"] },
  { name: "Xai Testnet v2", logoUrl: "/Chains/ethereum.svg", keywords: ["xai", "v2"] },
  { name: "ZKsync Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["zksync", "sepolia"] },
  { name: "ZERO Testnet (Sepolia)", logoUrl: "/Chains/ethereum.svg", keywords: ["zero", "sepolia"] },
  { name: "ZetaChain Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["zetachain"] },
  { name: "Zircuit Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["zircuit"] },
  { name: "Zora Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["zora", "sepolia"] },
  { name: "zkCandy Sepolia", logoUrl: "/Chains/ethereum.svg", keywords: ["zkcandy", "sepolia"] },
  { name: "00-Newton-Testnet", logoUrl: "/Chains/ethereum.svg", keywords: ["newton", "00-newton"] }
];
