export const links = {
	home: '/',
	twitter: 'https://x.com/concero_io',
	discord: 'https://discord.com/invite/nBMAdxYTZK',
	medium: 'https://medium.com/@concero',
	whitepaper: 'https://concero.io/v2_whitepaper.pdf',
	bridging_framework: 'https://concero.io/concero_liquidity_framework.pdf',
	documentation: 'https://docs.concero.io/',
	blog: 'https://blog.concero.io/',
	swap: 'https://app.lanca.io/',
	liquidity: 'https://app.lanca.io/pools',
	rewards: 'https://app.concero.io/rewards',
	scan: 'https://scan.concero.io/',
	github: 'https://github.com/concero',
	linkedin: 'https://www.linkedin.com/company/concero-io/posts/?feedView=all',
	overview: '/overview',
	lanca: '/lanca',
	depo: '',
	distro: '',
}
